feat: Product CRUD backend
simsve3/PVP_K264 pull request #4
Opened 2023-03-11 15:58 UTC by Viliusps

2023-03-11 16:03 UTC, simsve3 commented
Truksta foto saugojimo;
User modelyje padaryti sasaja, jog grazintu produktu lista kartu su nurodytu useriu

2023-03-11 16:26 UTC, Viliusps commented
> Truksta foto saugojimo; User modelyje padaryti sasaja, jog grazintu produktu lista kartu su nurodytu useriu

Sukurtas atskiras user story foto saugojimui

2023-03-11 18:30 UTC, mantux5 requested changes

2023-03-11 18:30 UTC, mantux5 commented on database/db/database.sql
> +    description       varchar(150) NOT NULL,
150 gali būti mažoka. text tiesiog būtų geriau manau

2023-03-11 18:30 UTC, mantux5 commented on database/db/database.sql
> +    created_by       INT NOT NULL,
Santykiai su kitomis lentelėmis dažniausiai turi tos lentelės pavadinimą. Tai `user_id` būtų tinkamiau manau

2023-03-11 18:42 UTC, simsve3 approved these changes

2023-03-11 18:49 UTC, simsve3 requested changes

2023-03-11 18:49 UTC, simsve3 commented on backend/eshop/src/main/java/com/pvp/eshop/model/Product.java
> +    private long created_by;
user_id vietoje created_by? Testavai ir sitaip veikia?

2023-03-11 18:49 UTC, simsve3 commented on backend/eshop/src/main/java/com/pvp/eshop/model/User.java
> +    private List<Product> products = new ArrayList<>();
Cia irgi created_by veikia?

2023-03-12 09:42 UTC, simsve3 approved these changes

2023-03-12 11:14 UTC, mantux5 approved these changes

2023-03-12 11:14 UTC, merged